// <auto-generated />
using System;
using APIClothesEcommerceShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIClothesEcommerceShop.Migrations
{
    [DbContext(typeof(EcommerceShopContext))]
    partial class EcommerceShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietcombohoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSp");

                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaCtsp", "MaCombo")
                        .HasName("PK__CHITIETC__9F02B7B6FFDE6FBA");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaCtsp");

                    b.ToTable("CHITIETCOMBOHOADON", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietdanhmuc", b =>
                {
                    b.Property<int>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMucCon")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.HasKey("MaDanhMucCha", "MaDanhMucCon", "MaSp")
                        .HasName("PK__CHITIETD__9C4F44F4B8B620B8");

                    b.HasIndex("MaDanhMucCon");

                    b.HasIndex("MaSp");

                    b.ToTable("CHITIETDANHMUC", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietsanpham", b =>
                {
                    b.Property<int>("MaCtsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtsp"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<string>("MauSac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaCtsp")
                        .HasName("PK__CHITIETS__1E4FCECD5A7581C1");

                    b.HasIndex("MaSp");

                    b.ToTable("CHITIETSANPHAM", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chucvu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__CHUCVU__D4639533D95BEECA");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<int>("GiaCombo")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCombo")
                        .HasName("PK__COMBO__C3EDBC788ACDE30D");

                    b.ToTable("COMBO", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Cthoadon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int>("GiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int?>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CTHOADON__3214EC272F449754");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaHd");

                    b.ToTable("CTHOADON", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Danhmuccha", b =>
                {
                    b.Property<int>("MaDanhMucCha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMucCha"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TenDanhMucCha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaDanhMucCha")
                        .HasName("PK__DANHMUCC__6719FD9E5876B596");

                    b.ToTable("DANHMUCCHA", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Danhmuccon", b =>
                {
                    b.Property<int>("MaDanhMucCon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMucCon"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TenDanhMucCon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaDanhMucCon")
                        .HasName("PK__DANHMUCC__6719C62F0C90C224");

                    b.ToTable("DANHMUCCON", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Giohang", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int?>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GIOHANG__3214EC27D6272CAB");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaKh");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Giohangctcombo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GIOHANGC__3214EC276D2330CA");

                    b.HasIndex("MaCtsp");

                    b.HasIndex("MaGioHang");

                    b.ToTable("GIOHANGCTCOMBO", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Hinhanh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int>("MaCtsp")
                        .HasColumnType("int")
                        .HasColumnName("MaCTSP");

                    b.Property<string>("TenHinhAnh")
                        .HasColumnType("text");

                    b.HasKey("MaHinhAnh")
                        .HasName("PK__HINHANH__A9C37A9B52310EEB");

                    b.HasIndex("MaCtsp");

                    b.ToTable("HINHANH", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<DateTime?>("BatDauGiao")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaChiNhanHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhThucTt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HinhThucTT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<decimal>("TienGoc")
                        .HasColumnType("decimal(11, 2)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHd")
                        .HasName("PK__HOADON__2725A6E074C6EE92");

                    b.HasIndex("MaCode");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("char(255)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("Sdt")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Đang hoạt động");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E44D7EB2D");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Macoupon", b =>
                {
                    b.Property<string>("MaCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<int>("DonHangToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("char(255)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<int>("SoTienGiam")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaCode")
                        .HasName("PK__MACOUPON__152C7C5D253AC471");

                    b.ToTable("MACOUPON", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("char(40)")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("char(255)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .IsFixedLength();

                    b.Property<string>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Đang hoạt động");

                    b.HasKey("MaNv")
                        .HasName("PK__NHANVIEN__2725D70A03818D9F");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Refreshtoken", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__REFRESHT__3214EC27840D2D6F");

                    b.ToTable("REFRESHTOKEN", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Sanpham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSp")
                        .HasName("PK__SANPHAM__2725081C19DDE914");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietcombohoadon", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Combo", "MaComboNavigation")
                        .WithMany("Chitietcombohoadons")
                        .HasForeignKey("MaCombo")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETCO__MaCom__6754599E");

                    b.HasOne("APIClothesEcommerceShop.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Chitietcombohoadons")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETCO__MaCTS__66603565");

                    b.HasOne("APIClothesEcommerceShop.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Chitietcombohoadons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETCOM__MaHD__656C112C");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietdanhmuc", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Danhmuccha", "MaDanhMucChaNavigation")
                        .WithMany("Chitietdanhmucs")
                        .HasForeignKey("MaDanhMucCha")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDA__MaDan__52593CB8");

                    b.HasOne("APIClothesEcommerceShop.Models.Danhmuccon", "MaDanhMucConNavigation")
                        .WithMany("Chitietdanhmucs")
                        .HasForeignKey("MaDanhMucCon")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDA__MaDan__534D60F1");

                    b.HasOne("APIClothesEcommerceShop.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietdanhmucs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDAN__MaSP__5441852A");

                    b.Navigation("MaDanhMucChaNavigation");

                    b.Navigation("MaDanhMucConNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietsanpham", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietsanphams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETSAN__MaSP__4F7CD00D");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Cthoadon", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Combo", "MaComboNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaCombo")
                        .HasConstraintName("FK__CTHOADON__MaComb__6C190EBB");

                    b.HasOne("APIClothesEcommerceShop.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__CTHOADON__MaCTSP__6B24EA82");

                    b.HasOne("APIClothesEcommerceShop.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaHD__6A30C649");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Giohang", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Combo", "MaComboNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaCombo")
                        .HasConstraintName("FK__GIOHANG__MaCombo__72C60C4A");

                    b.HasOne("APIClothesEcommerceShop.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaCtsp")
                        .HasConstraintName("FK__GIOHANG__MaCTSP__71D1E811");

                    b.HasOne("APIClothesEcommerceShop.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANG__MaKH__70DDC3D8");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Giohangctcombo", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Giohangctcombos")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANGCT__MaCTS__75A278F5");

                    b.HasOne("APIClothesEcommerceShop.Models.Giohang", "MaGioHangNavigation")
                        .WithMany("Giohangctcombos")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANGCT__MaGio__76969D2E");

                    b.Navigation("MaCtspNavigation");

                    b.Navigation("MaGioHangNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Hinhanh", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Chitietsanpham", "MaCtspNavigation")
                        .WithMany("Hinhanhs")
                        .HasForeignKey("MaCtsp")
                        .IsRequired()
                        .HasConstraintName("FK__HINHANH__MaCTSP__571DF1D5");

                    b.Navigation("MaCtspNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Hoadon", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Macoupon", "MaCodeNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaCode")
                        .HasConstraintName("FK__HOADON__MaCode__628FA481");

                    b.HasOne("APIClothesEcommerceShop.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKH__60A75C0F");

                    b.HasOne("APIClothesEcommerceShop.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HOADON__MaNV__619B8048");

                    b.Navigation("MaCodeNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Nhanvien", b =>
                {
                    b.HasOne("APIClothesEcommerceShop.Models.Chucvu", "MaChucVuNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaChucVu")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__MaChuc__4222D4EF");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chitietsanpham", b =>
                {
                    b.Navigation("Chitietcombohoadons");

                    b.Navigation("Cthoadons");

                    b.Navigation("Giohangctcombos");

                    b.Navigation("Giohangs");

                    b.Navigation("Hinhanhs");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Combo", b =>
                {
                    b.Navigation("Chitietcombohoadons");

                    b.Navigation("Cthoadons");

                    b.Navigation("Giohangs");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Danhmuccha", b =>
                {
                    b.Navigation("Chitietdanhmucs");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Danhmuccon", b =>
                {
                    b.Navigation("Chitietdanhmucs");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Giohang", b =>
                {
                    b.Navigation("Giohangctcombos");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Hoadon", b =>
                {
                    b.Navigation("Chitietcombohoadons");

                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Khachhang", b =>
                {
                    b.Navigation("Giohangs");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Macoupon", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("APIClothesEcommerceShop.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietdanhmucs");

                    b.Navigation("Chitietsanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
